### ISSUE TITLE
Colab run PCN-Pytorch

### ISSUE THREAD

**Issue by kafei123456** [qinglew/PCN-PyTorch#14]
colab:CUDA-10.1 ,pytorch1.7, python3.7
the trackback:
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from metrics.metric import l1_cd
  File "/content/drive/MyDrive/PCN-PyTorch/metrics/metric.py", line 5, in <module>
    from extensions.earth_movers_distance.emd import EarthMoverDistance
  File "/content/drive/MyDrive/PCN-PyTorch/extensions/earth_movers_distance/emd.py", line 3, in <module>
    import emd_cuda
ModuleNotFoundError: No module named 'emd_cuda'

I don't know the problom, when run PCN-pytorch in colab.and I have compiled the "earth_movers_distance" core.

Are there any solutions?

**Comment by hiepbk** [comment]
I think you haven't complied for emd and cd, refer this for colab:
%cd extensions/chamfer_distance
!python setup.py install
%cd ../earth_movers_distance
!python setup.py install

**Comment by kafei123456** [comment]
Think you for your valuable advices.
