### ISSUE TITLE
No module name Imath in process_exr.py

### ISSUE THREAD

**Issue by hiepbk** [qinglew/PCN-PyTorch#23]
Hello author,
I tried to run this file process_exr.py and got the error:
Traceback (most recent call last):
  File "process_exr.py", line 25, in <module>
    import Imath
ModuleNotFoundError: No module named 'Imath'
I tried to install Imath and OpenEXR from pip or conda, but it didn't work.

**Comment by hiepbk** [comment]
I already fixed this error by using this command:
pip --no-cache-dir install OpenEXR
It installed OpenEXR 1.38 with Imath.
However, there was a new error occurred:
  File "process_exr.py", line 26, in <module>
    import OpenEXR
ImportError: libIex-3_1.so.30: cannot open shared object file: No such file or directory
